version: '3.8'

services:
  # Serviciul pentru proxy-ul Nginx.
  webproxy:
    build:
      context: ./webproxy
      dockerfile: Dockerfile
    image: ghcr.io/nicoleta14/webproxy:latest
    container_name: webproxy
    ports:
      - "8080:80"
    volumes:
      - ./webproxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webserver1
      - webserver2
    restart: always

  # Primul server web Flask (Web Server 1).
  webserver1:
    build:
      context: ./webserver1
      dockerfile: Dockerfile
    image: ghcr.io/nicoleta14/webserver1:latest
    container_name: webserver1
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
      - FLASK_ENV=production
    depends_on:
      - redis
    restart: always

  # Al doilea server web Flask (Web Server 2).
  webserver2:
    build:
      context: ./webserver2
      dockerfile: Dockerfile
    image: ghcr.io/nicoleta14/webserver2:latest
    container_name: webserver2
    ports:
      - "5002:5000"
    environment:
      - REDIS_HOST=redis
      - FLASK_ENV=production
    depends_on:
      - redis
    restart: always

  # Serviciul pentru baza de date Redis.
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # Primul nod Cassandra.
  cassandra1:
    build:
      context: ./cassandra1
      dockerfile: Dockerfile
    image: ghcr.io/nicoleta14/cassandra1:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra1_data:/var/lib/cassandra
    restart: always

  # Al doilea nod Cassandra.
  cassandra2:
    build:
      context: ./cassandra2
      dockerfile: Dockerfile
    image: ghcr.io/nicoleta14/cassandra2:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    depends_on:
      - cassandra1
    volumes:
      - cassandra2_data:/var/lib/cassandra
    restart: always

# Volumele pentru stocare persistentă.
volumes:
  cassandra1_data:
  cassandra2_data:
  redis_data:
