name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: labb

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.LABB }}

      - name: Set repository name
        run: echo "REPO=lab2webproxy" >>${GITHUB_ENV}

      - name: Build and push container image for webserver1
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          tags: |
            ghcr.io/lab2webproxy:webserver1-latest
            ghcr.io/lab2webproxy:webserver1-${{ github.sha }}
          file: ./webserver1/Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.LABB3 }}
          images: 'ghcr.io/lab2webproxy:webserver1-latest'
