name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: labb  # Replace with the Azure Web App name

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub container registry
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.LABB }}  # Token is "labb"

      # Set repository name to Lab2WebProxy in lowercase
      - name: Set repository name
        run: echo "REPO=lab2webproxy" >>${GITHUB_ENV}

      # Build and push container image to registry
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:latest  # Use the repository name as "latest"
            ghcr.io/${{ env.REPO }}:${{ github.sha }}  # Tag with SHA
          file: ./webserver2/Dockerfile  # Update this path if needed

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Azure Web App name
          publish-profile: ${{ secrets.LABB3 }}  # Publish profile is "labb3"
          images: 'ghcr.io/lab2webproxy:latest'  # Use the repository name "Lab2WebProxy"
